<?php require('template/indexHeader.phtml')?>

    <div class="container-xl">
        <form class="indexForm" method="post" action="logIn.php">
            <?php
            if(isset($errorMessage)){
                echo '<div class="errorMessageDiv"><p class="errorMessage">' . $errorMessage . '</p></div>';
            }
            ?>
            <h2 id="logInHeading">Log In</h2>
            <label>Username or Email Address:</label>
            <input type="text" name="logIn" required>
            <label>Password:</label>
            <input type="text" name="password" placeholder="Password" required>
            <?php
            echo '<label>What is ' . $view->number1 . ' + ' . $view->number2 . ' ?</label>
                <input type="hidden" name="hiddenNumber1" value="' . $view->number1 . '">
                <input type="hidden" name="hiddenNumber2" value="' . $view->number2 . '">';
            ?>
            <input type="text" name="userEntryCaptcha" placeholder="Answer Here">
            <button type="submit" name="submit" class="btn btn-outline-secondary">Log In</button>
            <!-- Button trigger log in modal -->
            <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#logInModalLabel">Help</button>

            <!-- Log In Modal -->
            <div class="modal fade" id="logInModalLabel" tabindex="-1" role="dialog" aria-labelledby="logInModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="logInModalLabel">Log In Requirements</h5>
                            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">X</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <ul>
                                <li>You can use either your username or email address to sign in</li>
                                <li>You must enter the password you set when signing up</li>
                                <li>You must enter the correct answer to the security question</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <div class="container-xl">
        <form class="indexForm" method="post" action="register.php">
            <?php
            if(isset($responseMessage)){
                echo '<div class="errorMessageDiv"><p class="errorMessage">' . $responseMessage . '</p></div>';
            }
            ?>
            <h2 id="registerHeading">Register</h2>
            <label>First Name:</label>
            <input type="text" name="firstName" placeholder="First name" required>
            <label>Last Name:</label>
            <input type="text" name="lastName" placeholder="Last name" required>
            <label>Email Address:</label>
            <input type="text" name="email" placeholder="Email address" required>
            <label>Username:</label>
            <input type="text" name="username" placeholder="Username" required>
            <label>Password:</label>

            <input type="text" name="password" placeholder="Password" required>
            <button type="submit" name="register" class="btn btn-outline-secondary">Register</button>

            <!-- Button trigger password help modal -->
            <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#registerModalLabel">Help</button>

            <!-- Password Help Modal -->
            <div class="modal fade" id="registerModalLabel" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="registerModalLabel">Password Requirements</h5>
                            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">X</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <ul>
                                <li>Must be 8 or more characters</li>
                                <li>Must contain at least one capital letter</li>
                                <li>Must contain at least one number</li>
                                <li>Must contain at least one special character</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

<?php require('template/footer.phtml') ?>
